import java.util.ArrayList;
import java.util.Arrays;
import java.util.Random;

public class Vehicle
{
    private String color = "";
    private int topSpeed = 0;
    private double safetyRating = 0.0;
    private double mpg = 0.0;
    private double maxRange = 0.0;
    private Random rng = new Random();
    private final ArrayList<String> possibleColors = new ArrayList<>(Arrays.asList("red", "orange", "yellow", "green", "blue", "purple", "silver", "black", "white", "brown"));

    // no-arg constructor
    // if i don't write one, one will be generated by default
    public Vehicle()
    {
        color = possibleColors.get(rng.nextInt(possibleColors.size()));
        topSpeed = rng.nextInt(60, 200);
        safetyRating = Math.round(rng.nextDouble(0, 100) * 100) / 100.0;
        mpg = Math.round(rng.nextDouble(10.0, 40.0) * 100) / 100.0;
        maxRange = Math.round(rng.nextDouble(0.0, 1000.0) * 100) / 100.0;
    }

    public Vehicle(String color, int topSpeed, double safetyRating, double mpg, double range)
    {
        // bypasses encapsulation
//        this.color = color;
//        this.topSpeed = topSpeed;
//        this.safetyRating = safetyRating;
//        this.mpg = mpg;
        setColor(color);
        setTopSpeed(topSpeed);
        setSafetyRating(safetyRating);
        setMpg(mpg);
        setMaxRange(range);
    }

    public double getTankSize()
    {
        return maxRange / mpg;
    }

    public void setTopSpeed(int newTopSpeed)
    {
        if (newTopSpeed < 0)
        {
            this.topSpeed = 0;
        }
        else
        {
            this.topSpeed = newTopSpeed;
        }
    }

    public int getTopSpeed()
    {
        return topSpeed;
    }

    public String getColor()
    {
        return color;
    }

    public void setColor(String color)
    {
        color = color.toLowerCase();
        if (possibleColors.contains(color))
        {
            this.color = color;
        }

    }

    public double getSafetyRating()
    {
        return safetyRating;
    }

    public boolean setSafetyRating(double safetyRating)
    {
        if (safetyRating >= 0.0 && safetyRating <= 100.0)
        {
            this.safetyRating = safetyRating;
            return true;
        }
        return false;
    }

    public double getMpg()
    {
        return mpg;
    }

    public void setMpg(double mpg)
    {
        if (mpg >= 0)
        {
            this.mpg = mpg;
        }
    }

    public double getMaxRange()
    {
        return maxRange;
    }

    public void setMaxRange(double maxRange)
    {
        if (maxRange < 0)
        {
            this.maxRange = 0;
        }
        else
        {
            this.maxRange = maxRange;
        }
    }

    public Random getRng()
    {
        return rng;
    }
}
